import { describe, expect, it } from 'vitest'
import {
  COURSE_LIBRARY,
  COURSE_SELECTION_STORAGE_KEY,
  courseDefinitionForId,
  courseRunId,
  courseSessionId,
  courseSeedForId,
  dailyOpsDayKey,
  dailyOpsProfile,
  dailyOpsSeed,
  dailyOpsTimestampForDayKey,
  monthlyOpsMonthKey,
  monthlyOpsProfile,
  monthlyOpsSeed,
  monthlyOpsTimestampForMonthKey,
  normalizeCourseId,
  weeklyOpsProfile,
  weeklyOpsSeed,
  weeklyOpsTimestampForWeekKey,
  weeklyOpsWeekKey,
  readSelectedCourseId,
  resolveCourseDefinition,
  shouldResetSeededRandomWorldForStorageKey,
  writeSelectedCourseId,
} from '../src/systems/CourseLibrary'
import { clearOpsPad, findPlayableSpawn, isUsableAirfield } from '../src/world/terrainSample'
import { setWorldSeed } from '../src/world/noise'

describe('course library', () => {
  it('derives a unique public ID catalog from the authored entries', () => {
    const ids = COURSE_LIBRARY.map(course => course.id)
    expect(new Set(ids).size).toBe(ids.length)
    expect(ids).toContain('shoreline-run')
    expect(normalizeCourseId('range-sweep')).toBe('range-sweep')
    expect(normalizeCourseId('not-a-course')).toBe('random')
    expect(normalizeCourseId('not-a-course', 'shoreline-run')).toBe('shoreline-run')
    expect(normalizeCourseId('not-a-course', 'not-a-course' as never)).toBe('random')
  })

  it('keeps the random entry and fixed course contracts stable', () => {
    expect(COURSE_LIBRARY).toHaveLength(75)
    expect(courseDefinitionForId('missing').id).toBe('random')
    expect(courseSeedForId('random')).toBeUndefined()
    expect(courseSeedForId('free-flight')).toBeUndefined()
    expect(courseSeedForId('training-orbit')).toBe(1)
    expect(courseDefinitionForId('training-orbit').weather).toBe('clear')
    expect(courseDefinitionForId('training-orbit').timeOfDay).toBeCloseTo(0.5)
    expect(courseDefinitionForId('free-flight').profile).toBe('free')
    expect(courseRunId(courseDefinitionForId('free-flight'))).toBeNull()
    expect(courseDefinitionForId('precision-slalom').profile).toBe('slalom')
    expect(courseRunId(courseDefinitionForId('precision-slalom'))).toBe('seed:3:slalom')
    expect(courseDefinitionForId('ridge-run').profile).toBe('ridge')
    expect(courseRunId(courseDefinitionForId('ridge-run'))).toBe('seed:4:ridge')
    expect(courseDefinitionForId('canyon-run').profile).toBe('canyon')
    expect(courseRunId(courseDefinitionForId('canyon-run'))).toBe('seed:5:canyon')
    expect(courseDefinitionForId('coastal-run').profile).toBe('coast')
    expect(courseRunId(courseDefinitionForId('coastal-run'))).toBe('seed:6:coast')
    expect(courseDefinitionForId('fjord-run').profile).toBe('fjord')
    expect(courseDefinitionForId('fjord-run').weather).toBe('fog')
    expect(courseRunId(courseDefinitionForId('fjord-run'))).toBe('seed:13:fjord')
    expect(courseDefinitionForId('river-run').profile).toBe('river')
    expect(courseRunId(courseDefinitionForId('river-run'))).toBe('seed:7:river')
    expect(courseDefinitionForId('volcanic-run').profile).toBe('volcanic')
    expect(courseRunId(courseDefinitionForId('volcanic-run'))).toBe('seed:8:volcanic')
    expect(courseDefinitionForId('volcanic-ops').profile).toBe('volcanic')
    expect(courseDefinitionForId('volcanic-ops').weather).toBe('storm')
    expect(courseDefinitionForId('volcanic-ops').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('volcanic-ops'))).toBe('seed:83:volcanic')
    expect(courseDefinitionForId('rift-ops').profile).toBe('canyon')
    expect(courseDefinitionForId('rift-ops').weather).toBe('fog')
    expect(courseDefinitionForId('rift-ops').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('rift-ops'))).toBe('seed:611:canyon')
    expect(courseDefinitionForId('desert-dash').profile).toBe('desert')
    expect(courseRunId(courseDefinitionForId('desert-dash'))).toBe('seed:9:desert')
    expect(courseDefinitionForId('alpine-pass').profile).toBe('alpine')
    expect(courseRunId(courseDefinitionForId('alpine-pass'))).toBe('seed:12:alpine')
    expect(courseDefinitionForId('storm-run').profile).toBe('storm')
    expect(courseDefinitionForId('storm-run').weather).toBe('storm')
    expect(courseRunId(courseDefinitionForId('storm-run'))).toBe('seed:10:storm')
    expect(courseDefinitionForId('night-ops').profile).toBe('night')
    expect(courseDefinitionForId('night-ops').weather).toBe('fog')
    expect(courseDefinitionForId('night-ops').timeOfDay).toBeCloseTo(0.84)
    expect(courseRunId(courseDefinitionForId('night-ops'))).toBe('seed:11:night')
    expect(courseDefinitionForId('aurora-run').profile).toBe('night')
    expect(courseDefinitionForId('aurora-run').weather).toBe('clear')
    expect(courseDefinitionForId('aurora-run').timeOfDay).toBeCloseTo(0.84)
    expect(courseDefinitionForId('aurora-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('aurora-run'))).toBe('seed:512:night')
    expect(courseDefinitionForId('timberline-run').profile).toBe('timber')
    expect(courseRunId(courseDefinitionForId('timberline-run'))).toBe('seed:15:timber')
    expect(courseDefinitionForId('glacier-run').profile).toBe('glacier')
    expect(courseDefinitionForId('glacier-run').weather).toBe('snow')
    expect(courseRunId(courseDefinitionForId('glacier-run'))).toBe('seed:16:glacier')
    expect(courseDefinitionForId('frostline-ops').profile).toBe('glacier')
    expect(courseDefinitionForId('frostline-ops').weather).toBe('snow')
    expect(courseDefinitionForId('frostline-ops').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('frostline-ops'))).toBe('seed:902:glacier')
    expect(courseDefinitionForId('rainforest-run').profile).toBe('rainforest')
    expect(courseDefinitionForId('rainforest-run').weather).toBe('rain')
    expect(courseDefinitionForId('mesa-run').profile).toBe('mesa')
    expect(courseRunId(courseDefinitionForId('mesa-run'))).toBe('seed:18:mesa')
    expect(courseDefinitionForId('badlands-run').profile).toBe('badlands')
    expect(courseRunId(courseDefinitionForId('badlands-run'))).toBe('seed:26:badlands')
    expect(courseDefinitionForId('saltflat-run').profile).toBe('saltflat')
    expect(courseRunId(courseDefinitionForId('saltflat-run'))).toBe('seed:21:saltflat')
    expect(courseDefinitionForId('savanna-run').profile).toBe('savanna')
    expect(courseRunId(courseDefinitionForId('savanna-run'))).toBe('seed:22:savanna')
    expect(courseDefinitionForId('tundra-run').profile).toBe('tundra')
    expect(courseDefinitionForId('tundra-run').weather).toBe('snow')
    expect(courseRunId(courseDefinitionForId('tundra-run'))).toBe('seed:23:tundra')
    expect(courseDefinitionForId('tundra-ops').profile).toBe('tundra')
    expect(courseDefinitionForId('tundra-ops').weather).toBe('snow')
    expect(courseDefinitionForId('tundra-ops').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('tundra-ops'))).toBe('seed:931:tundra')
    expect(courseDefinitionForId('swamp-run').profile).toBe('swamp')
    expect(courseDefinitionForId('swamp-run').weather).toBe('rain')
    expect(courseRunId(courseDefinitionForId('swamp-run'))).toBe('seed:24:swamp')
    expect(courseDefinitionForId('monsoon-run').profile).toBe('monsoon')
    expect(courseDefinitionForId('monsoon-run').weather).toBe('rain')
    expect(courseDefinitionForId('monsoon-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('monsoon-run'))).toBe('seed:54:monsoon')
    expect(courseDefinitionForId('archipelago-run').profile).toBe('archipelago')
    expect(courseDefinitionForId('archipelago-run').weather).toBe('fog')
    expect(courseRunId(courseDefinitionForId('archipelago-run'))).toBe('seed:25:archipelago')
    expect(courseDefinitionForId('thermal-run').profile).toBe('thermal')
    expect(courseDefinitionForId('thermal-run').weather).toBe('clear')
    expect(courseRunId(courseDefinitionForId('thermal-run'))).toBe('seed:27:thermal')
    expect(courseDefinitionForId('pattern-approach').profile).toBe('approach')
    expect(courseDefinitionForId('pattern-approach').weather).toBe('clear')
    expect(courseRunId(courseDefinitionForId('pattern-approach'))).toBe('seed:28:approach')
    expect(courseDefinitionForId('crosswind-approach').profile).toBe('approach')
    expect(courseDefinitionForId('crosswind-approach').weather).toBe('storm')
    expect(courseDefinitionForId('crosswind-approach').windSide).toBe('right')
    expect(courseRunId(courseDefinitionForId('crosswind-approach'))).toBe('seed:29:approach')
    expect(courseDefinitionForId('traffic-run').profile).toBe('sweep')
    expect(courseDefinitionForId('traffic-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('traffic-run'))).toBe('seed:348:sweep')
    expect(courseDefinitionForId('waterway-tour').profile).toBe('river')
    expect(courseDefinitionForId('waterway-tour').weather).toBe('rain')
    expect(courseDefinitionForId('waterway-tour').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('waterway-tour'))).toBe('seed:54:river')
    expect(courseDefinitionForId('thermal-surf').profile).toBe('thermal')
    expect(courseDefinitionForId('thermal-surf').weather).toBe('clear')
    expect(courseDefinitionForId('thermal-surf').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('thermal-surf'))).toBe('seed:80:thermal')
    expect(courseDefinitionForId('high-dive').profile).toBe('alpine')
    expect(courseDefinitionForId('high-dive').weather).toBe('clear')
    expect(courseDefinitionForId('high-dive').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('high-dive'))).toBe('seed:102:alpine')
    expect(courseDefinitionForId('water-skim').profile).toBe('coast')
    expect(courseDefinitionForId('water-skim').weather).toBe('clear')
    expect(courseDefinitionForId('water-skim').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('water-skim'))).toBe('seed:121:coast')
    expect(courseDefinitionForId('ridge-trial').profile).toBe('ridge')
    expect(courseDefinitionForId('ridge-trial').weather).toBe('clear')
    expect(courseDefinitionForId('ridge-trial').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('ridge-trial'))).toBe('seed:115:ridge')
    expect(courseDefinitionForId('traffic-dodge').profile).toBe('sweep')
    expect(courseDefinitionForId('traffic-dodge').weather).toBe('clear')
    expect(courseDefinitionForId('traffic-dodge').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('traffic-dodge'))).toBe('seed:31:sweep')
    expect(courseDefinitionForId('precision-landing').profile).toBe('approach')
    expect(courseDefinitionForId('precision-landing').weather).toBe('clear')
    expect(courseDefinitionForId('precision-landing').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('precision-landing'))).toBe('seed:127:approach')
    expect(courseDefinitionForId('combo-run').profile).toBe('slalom')
    expect(courseDefinitionForId('combo-run').weather).toBe('clear')
    expect(courseDefinitionForId('combo-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('combo-run'))).toBe('seed:394:slalom')
    expect(courseDefinitionForId('night-flight').profile).toBe('night')
    expect(courseDefinitionForId('night-flight').weather).toBe('fog')
    expect(courseDefinitionForId('night-flight').timeOfDay).toBeCloseTo(0.84)
    expect(courseDefinitionForId('night-flight').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('night-flight'))).toBe('seed:463:night')
    expect(courseDefinitionForId('radar-run').profile).toBe('sweep')
    expect(courseDefinitionForId('radar-run').weather).toBe('clear')
    expect(courseDefinitionForId('radar-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('radar-run'))).toBe('seed:113:sweep')
    expect(courseDefinitionForId('precision-chain').profile).toBe('slalom')
    expect(courseDefinitionForId('precision-chain').weather).toBe('clear')
    expect(courseDefinitionForId('precision-chain').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('precision-chain'))).toBe('seed:45:slalom')
    expect(courseDefinitionForId('butter-landing').profile).toBe('approach')
    expect(courseDefinitionForId('butter-landing').weather).toBe('clear')
    expect(courseDefinitionForId('butter-landing').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('butter-landing'))).toBe('seed:222:approach')
    expect(courseDefinitionForId('dry-run').profile).toBe('sweep')
    expect(courseDefinitionForId('dry-run').weather).toBe('clear')
    expect(courseDefinitionForId('dry-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('dry-run'))).toBe('seed:63:sweep')
    expect(courseDefinitionForId('gust-rider').profile).toBe('storm')
    expect(courseDefinitionForId('gust-rider').weather).toBe('storm')
    expect(courseDefinitionForId('gust-rider').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('gust-rider'))).toBe('seed:361:storm')
    expect(courseDefinitionForId('range-run').profile).toBe('sweep')
    expect(courseDefinitionForId('range-run').weather).toBe('clear')
    expect(courseDefinitionForId('range-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('range-run'))).toBe('seed:417:sweep')
    expect(courseDefinitionForId('settlement-tour').profile).toBe('sweep')
    expect(courseDefinitionForId('settlement-tour').weather).toBe('clear')
    expect(courseDefinitionForId('settlement-tour').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('settlement-tour'))).toBe('seed:76:sweep')
    expect(courseDefinitionForId('airshow-run').profile).toBe('slalom')
    expect(courseDefinitionForId('airshow-run').weather).toBe('clear')
    expect(courseDefinitionForId('airshow-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('airshow-run'))).toBe('seed:19:slalom')
    expect(courseDefinitionForId('biome-tour').profile).toBe('sweep')
    expect(courseDefinitionForId('biome-tour').weather).toBe('clear')
    expect(courseDefinitionForId('biome-tour').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('biome-tour'))).toBe('seed:42:sweep')
    expect(courseDefinitionForId('scout-run').profile).toBe('sweep')
    expect(courseDefinitionForId('scout-run').weather).toBe('clear')
    expect(courseDefinitionForId('scout-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('scout-run'))).toBe('seed:32:sweep')
    expect(courseDefinitionForId('skyline-run').profile).toBe('alpine')
    expect(courseDefinitionForId('skyline-run').weather).toBe('clear')
    expect(courseDefinitionForId('skyline-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('skyline-run'))).toBe('seed:33:alpine')
    expect(courseDefinitionForId('speed-run').profile).toBe('sweep')
    expect(courseDefinitionForId('speed-run').weather).toBe('clear')
    expect(courseDefinitionForId('speed-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('speed-run'))).toBe('seed:20:sweep')
    expect(courseDefinitionForId('terrain-hugger').profile).toBe('canyon')
    expect(courseDefinitionForId('terrain-hugger').weather).toBe('clear')
    expect(courseDefinitionForId('terrain-hugger').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('terrain-hugger'))).toBe('seed:46:canyon')
    expect(courseDefinitionForId('fuel-saver').profile).toBe('sweep')
    expect(courseDefinitionForId('fuel-saver').weather).toBe('clear')
    expect(courseDefinitionForId('fuel-saver').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('fuel-saver'))).toBe('seed:38:sweep')
    expect(courseDefinitionForId('energy-run').profile).toBe('sweep')
    expect(courseDefinitionForId('energy-run').weather).toBe('clear')
    expect(courseDefinitionForId('energy-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('energy-run'))).toBe('seed:51:sweep')
    expect(courseDefinitionForId('storm-contract').profile).toBe('storm')
    expect(courseDefinitionForId('storm-contract').weather).toBe('storm')
    expect(courseDefinitionForId('storm-contract').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('storm-contract'))).toBe('seed:69:storm')
    expect(courseDefinitionForId('crosswind-run').profile).toBe('approach')
    expect(courseDefinitionForId('crosswind-run').weather).toBe('storm')
    expect(courseDefinitionForId('crosswind-run').windSide).toBe('right')
    expect(courseDefinitionForId('crosswind-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('crosswind-run'))).toBe('seed:216:approach')
    expect(courseDefinitionForId('mach-run').profile).toBe('sweep')
    expect(courseDefinitionForId('mach-run').weather).toBe('clear')
    expect(courseDefinitionForId('mach-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('mach-run'))).toBe('seed:57:sweep')
    expect(courseDefinitionForId('burn-run').profile).toBe('sweep')
    expect(courseDefinitionForId('burn-run').weather).toBe('clear')
    expect(courseDefinitionForId('burn-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('burn-run'))).toBe('seed:30:sweep')
    expect(courseDefinitionForId('g-control-run').profile).toBe('slalom')
    expect(courseDefinitionForId('g-control-run').weather).toBe('clear')
    expect(courseDefinitionForId('g-control-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('g-control-run'))).toBe('seed:247:slalom')
    expect(courseDefinitionForId('deadstick-run').profile).toBe('desert')
    expect(courseDefinitionForId('deadstick-run').weather).toBe('clear')
    expect(courseDefinitionForId('deadstick-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('deadstick-run'))).toBe('seed:99:desert')
    expect(courseDefinitionForId('clean-circuit-run').profile).toBe('desert')
    expect(courseDefinitionForId('clean-circuit-run').weather).toBe('clear')
    expect(courseDefinitionForId('clean-circuit-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('clean-circuit-run'))).toBe('seed:9:desert:clean-circuit')
    expect(courseRunId(courseDefinitionForId('clean-circuit-run')))
      .not.toBe(courseRunId(courseDefinitionForId('desert-dash')))
    expect(courseDefinitionForId('level-flight-run').profile).toBe('sweep')
    expect(courseDefinitionForId('level-flight-run').weather).toBe('clear')
    expect(courseDefinitionForId('level-flight-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('level-flight-run'))).toBe('seed:320:sweep')
    expect(courseDefinitionForId('water-run').profile).toBe('river')
    expect(courseDefinitionForId('water-run').weather).toBe('rain')
    expect(courseDefinitionForId('water-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('water-run'))).toBe('seed:4:river')
    expect(courseDefinitionForId('brake-check-run').profile).toBe('sweep')
    expect(courseDefinitionForId('brake-check-run').weather).toBe('clear')
    expect(courseDefinitionForId('brake-check-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('brake-check-run'))).toBe('seed:47:sweep')
    expect(courseDefinitionForId('thermal-control-run').profile).toBe('alpine')
    expect(courseDefinitionForId('thermal-control-run').weather).toBe('clear')
    expect(courseDefinitionForId('thermal-control-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('thermal-control-run'))).toBe('seed:2:alpine')
    expect(courseDefinitionForId('front-chaser-run').profile).toBe('storm')
    expect(courseDefinitionForId('front-chaser-run').weather).toBe('rain')
    expect(courseDefinitionForId('front-chaser-run').weatherShift).toBe('storm')
    expect(courseDefinitionForId('front-chaser-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('front-chaser-run'))).toBe('seed:259:storm')
    expect(courseDefinitionForId('shoreline-run').profile).toBe('coast')
    expect(courseDefinitionForId('shoreline-run').weather).toBe('fog')
    expect(courseDefinitionForId('shoreline-run').contractCatalog).toBe(true)
    expect(courseRunId(courseDefinitionForId('shoreline-run'))).toBe('seed:30:coast')
    expect(courseRunId(courseDefinitionForId('rainforest-run'))).toBe('seed:17:rainforest')
    expect(courseRunId(courseDefinitionForId('random'))).toBeNull()
    const daily = courseDefinitionForId('daily-ops')
    const dailyNow = Date.UTC(2026, 8, 28, 12)
    const dailyResolved = resolveCourseDefinition(daily, dailyNow)
    expect(daily.daily).toBe(true)
    expect(dailyResolved.seed).toBe(dailyOpsSeed(dailyNow))
    expect(dailyResolved.profile).toBe(dailyOpsProfile(dailyNow))
    expect(dailyResolved.detail).toContain(dailyOpsDayKey(dailyNow))
    expect(dailyOpsTimestampForDayKey(dailyOpsDayKey(dailyNow))).toBe(Date.UTC(2026, 8, 28, 12))
    expect(dailyOpsTimestampForDayKey('2026-02-30')).toBeNull()
    expect(courseRunId(daily, dailyNow)).toContain(`:daily:${dailyOpsDayKey(dailyNow)}`)
    expect(courseRunId(daily, dailyNow + 86_400_000)).not.toBe(courseRunId(daily, dailyNow))
    expect(courseSessionId('random', 42, 'orbit')).toBe('random-world')
    expect(courseSessionId('random', 42, 'orbit', undefined, true)).toBe('seed:42:orbit:custom')
    expect(courseSessionId('random', 42, 'orbit', undefined, true))
      .not.toBe(courseSessionId('random', 43, 'orbit', undefined, true))
    expect(courseSessionId('free-flight', 42, 'free')).toBe('free-flight')
    expect(courseSessionId('training-orbit', 1, 'orbit')).toBe('seed:1:orbit')
    expect(courseSessionId('clean-circuit-run', 9, 'desert')).toBe('seed:9:desert:clean-circuit')
    expect(courseSessionId('clean-circuit-run', 9, 'desert'))
      .not.toBe(courseSessionId('desert-dash', 9, 'desert'))
    expect(courseSessionId('training-orbit', Number.NaN, 'orbit')).toBe('seed:0:orbit')
    expect(courseSessionId('daily-ops', dailyResolved.seed!, dailyResolved.profile!, dailyOpsDayKey(dailyNow)))
      .toBe(`${courseRunId(daily, dailyNow)}`)
    const weekly = courseDefinitionForId('weekly-ops')
    const weeklyNow = Date.UTC(2026, 8, 28, 12)
    const weeklyResolved = resolveCourseDefinition(weekly, weeklyNow)
    expect(weekly.weekly).toBe(true)
    expect(weeklyResolved.seed).toBe(weeklyOpsSeed(weeklyNow))
    expect(weeklyResolved.profile).toBe(weeklyOpsProfile(weeklyNow))
    expect(weeklyResolved.detail).toContain(weeklyOpsWeekKey(weeklyNow))
    expect(weeklyOpsTimestampForWeekKey(weeklyOpsWeekKey(weeklyNow))).toBe(Date.UTC(2026, 8, 28, 12))
    expect(weeklyOpsTimestampForWeekKey('2026-W00')).toBeNull()
    expect(courseRunId(weekly, weeklyNow)).toContain(`:weekly:${weeklyOpsWeekKey(weeklyNow)}`)
    expect(courseRunId(weekly, weeklyNow + 7 * 86_400_000)).not.toBe(courseRunId(weekly, weeklyNow))
    expect(courseSessionId('weekly-ops', weeklyResolved.seed!, weeklyResolved.profile!, weeklyOpsWeekKey(weeklyNow)))
      .toBe(`${courseRunId(weekly, weeklyNow)}`)
    const monthly = courseDefinitionForId('monthly-ops')
    const monthlyNow = Date.UTC(2026, 8, 28, 12)
    const monthlyResolved = resolveCourseDefinition(monthly, monthlyNow)
    expect(monthly.monthly).toBe(true)
    expect(monthlyResolved.seed).toBe(monthlyOpsSeed(monthlyNow))
    expect(monthlyResolved.profile).toBe(monthlyOpsProfile(monthlyNow))
    expect(monthlyResolved.detail).toContain(monthlyOpsMonthKey(monthlyNow))
    expect(monthlyOpsMonthKey(monthlyNow)).toBe('2026-09')
    expect(monthlyOpsTimestampForMonthKey(monthlyOpsMonthKey(monthlyNow))).toBe(Date.UTC(2026, 8, 15, 12))
    expect(monthlyOpsTimestampForMonthKey('2026-13')).toBeNull()
    expect(monthlyOpsTimestampForMonthKey('2026-09-01')).toBeNull()
    expect(monthlyOpsMonthKey(Number.MAX_VALUE)).toBe('2025-01')
    expect(monthlyOpsSeed(Number.MAX_VALUE)).toBe(monthlyOpsSeed(Date.UTC(2025, 0, 1, 12)))
    expect(monthlyOpsProfile(Number.MAX_VALUE)).toBe(monthlyOpsProfile(Date.UTC(2025, 0, 1, 12)))
    expect(courseRunId(monthly, monthlyNow)).toContain(`:monthly:${monthlyOpsMonthKey(monthlyNow)}`)
    expect(courseRunId(monthly, Date.UTC(2026, 9, 1, 12))).not.toBe(courseRunId(monthly, monthlyNow))
    expect(courseSessionId('monthly-ops', monthlyResolved.seed!, monthlyResolved.profile!, monthlyOpsMonthKey(monthlyNow)))
      .toBe(`${courseRunId(monthly, monthlyNow)}`)
  })

  it('persists only valid course ids and fails closed on storage denial', () => {
    const values = new Map<string, string>()
    const storage = {
      getItem: (key: string) => values.get(key) ?? null,
      setItem: (key: string, value: string) => values.set(key, value),
    }
    expect(readSelectedCourseId(storage)).toBe('random')
    writeSelectedCourseId(storage, 'range-sweep')
    expect(readSelectedCourseId(storage)).toBe('range-sweep')
    writeSelectedCourseId(storage, 'not-a-course' as never)
    expect(values.get(COURSE_SELECTION_STORAGE_KEY)).toBe('random')
    values.set(COURSE_SELECTION_STORAGE_KEY, 'not-a-course')
    expect(readSelectedCourseId(storage)).toBe('random')
    expect(() => writeSelectedCourseId(null, 'training-orbit')).not.toThrow()
  })

  it('invalidates in-memory seeded-world identity only for selection resets', () => {
    expect(shouldResetSeededRandomWorldForStorageKey(COURSE_SELECTION_STORAGE_KEY)).toBe(true)
    expect(shouldResetSeededRandomWorldForStorageKey(null)).toBe(true)
    expect(shouldResetSeededRandomWorldForStorageKey('blackout.course-recents')).toBe(false)
  })

  it('keeps every authored course record identity unique', () => {
    const identities = COURSE_LIBRARY
      .map(courseRunId)
      .filter((identity): identity is string => identity !== null)
    expect(new Set(identities).size).toBe(identities.length)
  })

  it('validates every curated seed to a usable dry airfield', () => {
    for (const course of COURSE_LIBRARY) {
      const resolved = resolveCourseDefinition(course, Date.UTC(2026, 8, 28, 12))
      if (resolved.seed === null) continue
      setWorldSeed(resolved.seed)
      clearOpsPad()
      const pad = findPlayableSpawn()
      expect(pad, `${course.id} should resolve a spawn`).not.toBeNull()
      expect(isUsableAirfield(pad!)).toBe(true)
    }
  }, 60_000)
})
